/**
 * Builds feature_spec.json (ARCHITECTURE.md §6): the contract between the
 * TypeScript feature code and the Python training code.
 *
 * `code_hash` is a SHA-256 over the spec body and every source file under
 * src/core/features and src/core/window (line endings normalised), so any
 * change to how features are computed changes the hash. A model trained on
 * one hash is refused by a browser running another (TODO C4).
 */
import { createHash } from 'node:crypto';
import { readdir, readFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { featureSpecBody } from '../src/core/features/spec.js';

export const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const SPEC_PATH = join(PACKAGE_ROOT, 'public', 'models', 'classifier', 'feature_spec.json');
const HASHED_DIRS = ['src/core/features', 'src/core/window'];

export async function buildFeatureSpec(): Promise<string> {
  const body = featureSpecBody();
  const hash = createHash('sha256');
  hash.update(canonicalJson(body));
  for (const file of await sourceFiles()) {
    const text = (await readFile(file, 'utf8')).replace(/\r\n/g, '\n');
    hash.update(`\n--- ${relative(PACKAGE_ROOT, file).replace(/\\/g, '/')}\n`);
    hash.update(text);
  }
  const spec = {
    $comment:
      'Generated by `pnpm feature-spec` from src/core/features. Do not edit. Training reads this; the browser refuses a model whose code_hash differs.',
    code_hash: hash.digest('hex'),
    ...body,
  };
  return `${JSON.stringify(spec, null, 2)}\n`;
}

async function sourceFiles(): Promise<string[]> {
  const files: string[] = [];
  for (const dir of HASHED_DIRS) {
    const abs = join(PACKAGE_ROOT, dir);
    for (const entry of await readdir(abs, { withFileTypes: true, recursive: true })) {
      if (entry.isFile() && entry.name.endsWith('.ts'))
        files.push(join(entry.parentPath, entry.name));
    }
  }
  return files.sort((a, b) => a.localeCompare(b));
}

/** JSON with object keys sorted, so the hash does not depend on key order. */
function canonicalJson(value: unknown): string {
  return JSON.stringify(value, (_key, v: unknown) =>
    v !== null && typeof v === 'object' && !Array.isArray(v)
      ? Object.fromEntries(
          Object.entries(v as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)),
        )
      : v,
  );
}
